chat/urls.py
from django.urls import path
from . import views

app_name = "chat"
urlpatterns = [
    path("message/<str:username>/", views.start_conversation, name="start-convo"),
    path(
        "conversation/<int:conversation_id>/", views.conversation, name="conversation"
    ),
    path("conversations/", views.conversations, name="conversations"),
]

friendship/urls.py
from django.urls import path
from friendship import views


app_name = "friendship"
urlpatterns = [
    path("friends/", views.friends, name="friendship"),
    path("<str:username>/accept", views.accept_request, name="accept-request"),
    path("<str:username>/reject", views.reject_request, name="reject-request"),
]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.UserLogoutView.as_view(), name="logout"),
    path("profile/", views.profile, name="profile"),
]

users/models.py
from hashlib import md5
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, AbstractUser
from django.core.validators import EmailValidator
from django.db import models
from django.utils import timezone


class MyUserManager(BaseUserManager):
    def _create_user(self, username, email, password):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError("Email Address must be provided")
        if not username:
            raise ValueError("Username must be provided")

        email = self.normalize_email(email)
        username = self.model.normalize_username(username)
        user = self.model(username=username, email=email)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, username, password=None):
        return self._create_user(username, email, password)

    def create_superuser(self, username, email, password=None):
        user = self.create_user(email, username, password)
        user.is_admin = True
        user.save(using=self._db)
        return user


class MyUser(AbstractBaseUser):
    email = models.EmailField(unique=True, validators=[EmailValidator()])
    username = models.CharField(unique=True, max_length=30)
    is_active = models.BooleanField(
        "active",
        default=True,
        help_text="Designates whether this user should be treated as active. "
        "Unselect this instead of deleting accounts.",
    )
    is_admin = models.BooleanField(
        "admin status",
        default=False,
        help_text="Designates whether the user can log into this admin site.",
    )
    date_joined = models.DateTimeField("date joined", default=timezone.now)

    REQUIRED_FIELDS = ["username"]
    USERNAME_FIELD = "email"
    objects = MyUserManager()

    def __str__(self):
        return self.email

    @property
    def avatar(self):
        digest = md5(self.email.lower().encode("utf-8")).hexdigest()
        return "https://www.gravatar.com/avatar/{}?d=identicon&s=64".format(digest)

    def has_perm(self, perm, obj=None):
        """Does the user have a specific permission?"""
        # Simplest possible answer: Yes, always
        return True

    def has_module_perms(self, app_label):
        """Does the user have permissions to view the app `app_label`?"""
        # Simplest possible answer: Yes, always
        return True

    @property
    def is_staff(self):
        return self.is_admin

    class Meta:
        verbose_name = "User"
        verbose_name_plural = "Users"

users/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import MyUser


class UserCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""

    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput,
        help_text="Password must be a minimum of 6 characters.",
        min_length=6,
    )
    password2 = forms.CharField(
        label="Password confirmation",
        widget=forms.PasswordInput,
        min_length=6,
        help_text="Enter the same password as before, for verification.",
    )

    class Meta:
        model = MyUser
        fields = ("username", "email")

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """

    password = ReadOnlyPasswordHashField()

    class Meta:
        model = MyUser
        fields = ("username", "email", "password", "is_active", "is_admin")

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]

users/views.py
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import render, redirect
from django.urls import reverse

from .forms import UserCreationForm


# Create your views here.


def register(request):
    form = UserCreationForm()
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            messages.success(request, "Account created successfully")
            return redirect(reverse("users:login"))
    return render(
        request, "users/register.html", {"title": "Create Account", "form": form}
    )


@login_required
def profile(request):
    return render(
        request,
        "users/profile.html",
        {"title": "Profile", "avatar": request.user.avatar},
    )


class UserLoginView(LoginView, SuccessMessageMixin):
    template_name = "users/login.html"
    extra_context = {"title": "Log In"}
    redirect_authenticated_user = True
    success_message = "Logged In Successfully"


class UserLogoutView(LogoutView, SuccessMessageMixin):
    template_name = "users/logout.html"
    success_message = "Logged Out Successfully"

users/templates/users/login.html
{% extends 'main/layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form action="{% url 'users:login' %}" method="post" class="mt-5 ">
    {% csrf_token %}
        <fieldset>
            <legend>Log In Account - Chat App</legend>
            {{ form|crispy }}
            <p class="">Don't have an account yet? <a href="{% url 'users:register' %}">Register</a></p>
            <button type="submit" class="btn btn-primary">Log In</button>
        </fieldset>
    </form>
{% endblock content %}

users/templates/users/logout.html
{% extends 'main/layout.html' %}
{% block content %}
    <div class="text-center" style="margin-top: 180px!important;">
        <h1 class="display-4">You have been logged out!</h1>
        <p class="lead"><a href="{% url 'users:login' %}">Log in again</a></p>
    </div>
{% endblock content %}

users/templates/users/profile.html
{% extends 'main/layout.html' %}
{% block content %}
    <nav class="nav nav-tabs justify-content-around">
        <a class="nav-item nav-link h3" href="{% url 'chat:conversations' %}">
            <span class="d-none d-sm-inline">Messages</span>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-chat-right-text" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M2 1h12a1 1 0 0 1 1 1v11.586l-2-2A2 2 0 0 0 11.586 11H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1zm12-1a2 2 0 0 1 2 2v12.793a.5.5 0 0 1-.854.353l-2.853-2.853a1 1 0 0 0-.707-.293H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h12z"/>
                <path fill-rule="evenodd" d="M3 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 6a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 6zm0 2.5a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5z"/>
            </svg>
        </a>
        <a class="nav-item nav-link h3" href="{% url 'friendship:friendship' %}">
            <span class="d-none d-sm-inline">Friends</span>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-plus" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M11 14s1 0 1-1-1-4-6-4-6 3-6 4 1 1 1 1h10zm-9.995-.944v-.002.002zM1.022 13h9.956a.274.274 0 0 0 .014-.002l.008-.002c-.001-.246-.154-.986-.832-1.664C9.516 10.68 8.289 10 6 10c-2.29 0-3.516.68-4.168 1.332-.678.678-.83 1.418-.832 1.664a1.05 1.05 0 0 0 .022.004zm9.974.056v-.002.002zM6 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4zm3-2a3 3 0 1 1-6 0 3 3 0 0 1 6 0zm4.5 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/>
                <path fill-rule="evenodd" d="M13 7.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0v-2z"/>
            </svg>
        </a>
        <a class="nav-item nav-link active h3" href="{% url 'users:profile' %}" >
            <span class="d-none d-sm-inline">Profile</span>
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-person-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                <path d="M13.468 12.37C12.758 11.226 11.195 10 8 10s-4.757 1.225-5.468 2.37A6.987 6.987 0 0 0 8 15a6.987 6.987 0 0 0 5.468-2.63z"/>
                <path fill-rule="evenodd" d="M8 9a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                <path fill-rule="evenodd" d="M8 1a7 7 0 1 0 0 14A7 7 0 0 0 8 1zM0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8z"/>
            </svg>
        </a>
    </nav>
    <div class="d-flex justify-content-center mt-5">
        <div class="text-center">
            <img src="{{ avatar }}" alt="User Profile" class="img-fluid mb-3">
            <h1 class="lead">Username: {{ user.username }}</h1>
            <p class="lead">Email: {{ user.email }}</p>
            <p class="lead">Joined: {{ user.date_joined|date }}</p>
            <a class="btn btn-danger" href="{% url 'users:logout' %}" role="button">Logout</a>
        </div>
    </div>
{% endblock content %}

users/templates/users/register.html
{% extends 'main/layout.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <form action="{% url 'users:register' %}" method="post" class="mt-5 ">
    {% csrf_token %}
        <fieldset>
            <legend>Create Account - Chat App</legend>
            {{ form|crispy }}
            <p>Already created an account? <a href="{% url 'users:login' %}">Log In</a></p>
            <button type="submit" class="btn btn-primary">Create Account</button>
        </fieldset>
    </form>
{% endblock content %}